# vim: noexpandtab:ts=4:sw=4

# Copyright 2015 Carsten Klein
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

artwork_dir     =
#artwork_dir     = ../pingo-artwork
project_dirs    = ../pingo-common
#project_dirs    = ../pingo ../pingo-common

deploy_name		= "pingo"
deploy_fqdn		= "es.coldrye.eu"
deploy_host		= "coldrye.eu"
deploy_user		= "root"
deploy_root		= "/var/www/sites"
deploy_conf		= "/etc/nginx"

